### ISSUE TITLE
Choose documentation platform

### ISSUE THREAD

**Issue by vojtatom** [vojtatom/metacity#12]
Suggest system form documentation. Generation of docs from code is preferred, target formats html or markdown. 

*Use online platforms* (language independent, you can add videos and pictures easily):
- https://www.gitbook.com 
- https://readthedocs.org
- github-pages 

*Auto generate from code* (faster to write, not as user friendly, standard for programmers, sometimes language dependent):
- https://github.com/jsdoc/jsdoc

**Comment by musarosro** [comment]
Nothing better found. Most of the docs would probably need to be created from scratch (no auto-generation possible), definitions and declarations,parameters and methods catalogue -> possible to use https://github.com/jsdoc/jsdoc
